export const COLOR_PRESETS = [
  { name: '검정', hex: '#333333' },
  { name: '흰색', hex: '#FFFFFF' },
  { name: '아이보리', hex: '#FFFFF0' },
  { name: '회색', hex: '#808080' },
  { name: '차콜', hex: '#555555' },
  { name: '크림', hex: '#FFFDD0' },
  { name: '베이지', hex: '#F5E6D3' },
  { name: '브라운', hex: '#4B3621' },
  { name: '카키', hex: '#8B7D5B' },
  { name: '올리브', hex: '#6B8E23' },
  { name: '네이비', hex: '#1E3A8A' },
  { name: '데님', hex: '#1560BD' },
  { name: '스카이블루', hex: '#87CEEB' },
  { name: '파랑', hex: '#4488FF' },
  { name: '민트', hex: '#34D399' },
  { name: '초록', hex: '#44BB44' },
  { name: '빨강', hex: '#FF4444' },
  { name: '버건디', hex: '#800020' },
  { name: '와인', hex: '#722F37' },
  { name: '코랄', hex: '#FF7F7F' },
  { name: '분홍', hex: '#FF88AA' },
  { name: '라벤더', hex: '#B4A7D6' },
  { name: '주황', hex: '#FF8844' },
  { name: '머스타드', hex: '#E1AD01' },
  { name: '노랑', hex: '#FFCC00' },
];
